Fix direct-listings/get-all example and add descriptions to status enum
thirdweb-dev/engine pull request #778
Opened 2024-11-21 22:37 UTC by dirtycajunrice

## Changes

- Linear: https://linear.app/thirdweb/issue/INF-171/
- Here is the problem being solved.
- Here are the changes made.

## How this PR will be tested

- [ ] Open the dashboard and click X. Result: A modal should appear.
- [ ] Call the /foo/bar API. Result: Returns 200 with "baz" in the response body.

## Output

(Example: Screenshot/GIF for UI changes, cURL output for API changes)

2024-11-21 22:37 UTC, dirtycajunrice commented
* **#778** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/engine/778?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/thirdweb-dev/engine/778?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-26 09:35 UTC, d4mr requested changes
would need to make a pass, remove es-lint related stuff and ignore autogen sdk code for formatter to get a more usable diff

2024-11-26 09:43 UTC, dirtycajunrice commented on eslint.config.mjs
I didnt add anything, i just migrated the existing config that already existed to one that didnt break.

2024-12-08 00:57 UTC, closed without merging

2024-12-10 10:33 UTC, arcoraven commented
I'm pulling pieces from this PR and merging them into main. I won't reopen this unless you want to rebase it (probably more effort than it's worth).